<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="https://maven.apache.org/POM/4.0.0"
  xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>net.tacticalmediafiles</groupId>
  <artifactId>tmf</artifactId>
  <version>2.1</version>
  <packaging>war</packaging>
  <name>tacticalmediafiles.net</name>
  <description>Tactical Media Files on MMBase 1.9</description>
  <properties>
    <mmbase.version.number>1.9</mmbase.version.number>
    <mmbase.version.postfix>-SNAPSHOT</mmbase.version.postfix>
    <mmbase.version>${mmbase.version.number}${mmbase.version.postfix}</mmbase.version>
    <base.version>${mmbase.version.number}${mmbase.version.postfix}</base.version>
    <mmbase.core>mmbase</mmbase.core>
    <mmbase.streams.version>1.9-SNAPSHOT</mmbase.streams.version>
    <mmbase.base-webapp.version>1.9-SNAPSHOT</mmbase.base-webapp.version>
    <saxon.version>9.1.0.6</saxon.version>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>

  <build>
    <defaultGoal>package</defaultGoal>
    <resources>
      <resource>
        <targetPath>org/mmbase/config</targetPath>
        <directory>src/main/config</directory>
        <includes>
          <include>**/*</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.mmbase.maven</groupId>
        <artifactId>maven-mmbase-plugin</artifactId>
        <version>1.9.7-rc2</version>
        <executions>
          <execution>
            <id>create-index-files</id>
            <goals>
              <goal>create-index-files</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>native2ascii-maven-plugin</artifactId>
        <version>2.0.1</version>
        <executions>
          <execution>
            <goals>
              <goal>resources</goal>
            </goals>
            <configuration>
              <encoding>UTF8</encoding>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.15.0</version>
        <configuration>
          <source>8</source>
          <target>8</target>
          <maxmem>256M</maxmem>
          <showDeprecation>true</showDeprecation>
        </configuration>
      </plugin>

      <!-- <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>buildnumber-maven-plugin</artifactId>
        <version>1.0-beta-4</version>
        <configuration>
          <buildNumberPropertyName>sources.version</buildNumberPropertyName>
          <timestampPropertyName>timestamp</timestampPropertyName>
          <timestampFormat>{0,date,yyyy-MM-dd'T'HH:mm}</timestampFormat>
          <doCheck>${buildnumber.doCheck}</doCheck>
          <doUpdate>true</doUpdate>
        </configuration>
        <executions>
          <execution>
            <phase>validate</phase>
            <goals>
              <goal>create</goal>
            </goals>
          </execution>
        </executions>
      </plugin> -->

      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <archiveClasses>true</archiveClasses>
          <overlays>
            <overlay>
              <groupId>org.mmbase.tinymce</groupId>
              <artifactId>tinymce-jquery</artifactId>
              <type>war</type>
            </overlay>
          </overlays>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
            </manifest>
            <manifestEntries>
              <url>${project.url}</url>
            </manifestEntries>
            <manifestSections>
              <manifestSection>
                <name>net.tacticalmediafiles</name>
                <manifestEntries>
                  <Vendor>Tactical Media Files</Vendor>
                  <Version>${project.version}</Version>
                  <SCM-Revision>${sources.version}</SCM-Revision>
                  <Distribution>${project.version}</Distribution>
                  <Build-Date>${timestamp}</Build-Date>
                  <!-- <Description>${project.description}</Description -->
                </manifestEntries>
              </manifestSection>
            </manifestSections>
          </archive>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-maven-plugin</artifactId>
        <version>10.0.26</version>
        <configuration>
          <webApp>
            <jettyEnvXml>${basedir}/jetty-env.xml</jettyEnvXml>
          </webApp>
          <systemProperties>
            <basedir>${project.basedir}</basedir>
            <com.sun.management.jmxremote />
            <java.awt.headless>true</java.awt.headless>
            <org.mmbase.XSLTransformer.validation>false</org.mmbase.XSLTransformer.validation>
            <org.mortbay.util.FileResource.checkAliases>false</org.mortbay.util.FileResource.checkAliases>
          </systemProperties>
        </configuration>
        <!--
            These jars are needed by jetty-env.xml
            which is used on mvn jetty:run
        -->
        <dependencies>
          <dependency>
            <groupId>c3p0</groupId>
            <artifactId>c3p0</artifactId>
            <version>0.9.1.2</version>
            <scope>runtime</scope>
          </dependency>
          <dependency>
            <groupId>hsqldb</groupId>
            <artifactId>hsqldb</artifactId>
            <version>1.8.0.10</version>
            <scope>runtime</scope>
          </dependency>
          <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.5.7</version>
            <scope>runtime</scope>
          </dependency>
          <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>javax.mail-api</artifactId>
            <version>1.6.2</version>
          </dependency>
        </dependencies>

      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>3.5.0</version>
        <executions>
          <execution>
            <id>enforce</id>
            <phase>validate</phase>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireJavaVersion>
                  <version>[1.8, 25]</version>
                </requireJavaVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-release-plugin</artifactId>
        <version>3.3.1</version>
        <configuration>
          <tagNameFormat>v${project.version}</tagNameFormat>
          <branchName>release-${project.version}</branchName>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.mmbase</groupId>
      <artifactId>base-webapp</artifactId>
      <version>${mmbase.base-webapp.version}</version>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>org.mmbase</groupId>
      <artifactId>mmbase-resources</artifactId>
      <version>${mmbase.streams.version}</version>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>org.mmbase</groupId>
      <artifactId>mmbase</artifactId>
      <version>${mmbase.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.mmbase</groupId>
      <artifactId>mmbase-streams</artifactId>
      <version>${mmbase.streams.version}</version>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>org.mmbase</groupId>
      <artifactId>mmbase-lucene</artifactId>
      <version>${mmbase.version}</version>
      <type>war</type>
    </dependency>

    <dependency>
      <groupId>org.mmbase</groupId>
      <artifactId>mmbase-crontab</artifactId>
      <version>${mmbase.version}</version>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>org.mmbase</groupId>
      <artifactId>mmbase-email</artifactId>
      <version>${mmbase.version}</version>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>org.mmbase</groupId>
      <artifactId>mmbase-editwizard</artifactId>
      <version>${mmbase.version}</version>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>org.mmbase</groupId>
      <artifactId>mmbase-media</artifactId>
      <version>${mmbase.version}</version>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>servlet-api</artifactId>
      <version>2.5</version>
      <scope>provided</scope>
    </dependency>

    <!-- a decent xslt processor is always welcome -->
    <dependency>
      <groupId>net.sf.saxon</groupId>
      <artifactId>saxon</artifactId>
      <version>8.7</version>
    </dependency>

    <dependency>
      <groupId>net.sf.saxon</groupId>
      <artifactId>saxon-dom</artifactId>
      <version>8.7</version>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>opensymphony</groupId>
      <artifactId>oscache</artifactId>
      <version>2.4</version>
      <exclusions>
        <exclusion>
          <!-- provided by base-webapp -->
          <groupId>log4j</groupId>
          <artifactId>log4j</artifactId>
        </exclusion>
        <exclusion>
          <!-- provided by lucene war -->
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
        <exclusion>
          <!-- this is a bug in the oscache pom, if you ask me -->
          <groupId>javax.servlet</groupId>
          <artifactId>servlet-api</artifactId>
        </exclusion>
        <exclusion>
          <!-- not available in Maven Central -->
          <groupId>javax.jms</groupId>
          <artifactId>jms</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.mmbase.tinymce</groupId>
      <artifactId>tinymce-jquery</artifactId>
      <version>3.2.7</version>
      <type>war</type>
    </dependency>

    <!--
        These jars are needed by jetty-env.xml
        which is used on mvn jetty:run
    -->

    <!-- 
    <dependency>
      <groupId>c3p0</groupId>
      <artifactId>c3p0</artifactId>
      <version>0.9.1.2</version>
      <scope>runtime</scope>
    </dependency> -->
    <dependency>
      <groupId>hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <version>1.8.0.10</version>
      <scope>runtime</scope>
    </dependency>

  </dependencies>

  <repositories>
    <repository>
      <name>Central Portal Snapshots</name>
      <id>central-snapshots</id>
      <url>https://central.sonatype.com/repository/maven-snapshots/</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>central-snapshots</id>
      <url>https://central.sonatype.com/repository/maven-snapshots/</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>

  <profiles>
    <profile>
      <id>development</id>
      <properties>
        <maven.war.useDefaultExcludes>false</maven.war.useDefaultExcludes>
      </properties>
    </profile>
  </profiles>


</project>
